version: 1
jobs:
  test1:
    image: node:10
    script:
        - npm install
        - ./node_modules/.bin/truffle test ./test/simplestorage.js
  test2:
    image: node:10
    script:
        - npm install
        - ./node_modules/.bin/truffle test ./test/TestSimpleStorage.sol
  build:
    image: docker:git
    services:
    - docker:dind
    script:
    - apk add npm python make g++
    - npm install
    - ./node_modules/.bin/truffle compile
    - IMAGE_VERSION=$(git rev-parse HEAD)
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build --build-arg VERSION=$IMAGE_VERSION -t $CI_REGISTRY_IMAGE:$IMAGE_VERSION -f ./Dockerfile .
    - docker push $CI_REGISTRY_IMAGE:$IMAGE_VERSION
  deploy_to_rinkeby:
      image: docker:git
      services:
      - docker:dind
      type: 
        ethereum/deploy: 
          signing: false
          record: true
      script:
      - IMAGE_VERSION=$(git rev-parse HEAD)
      - docker pull $CI_REGISTRY_IMAGE:$IMAGE_VERSION
      - docker run --rm -i -e MNEMONIC="${MNEMONIC}" -e INFURA_API_KEY=${INFURA_API_KEY} -e NETWORK=rinkeby $CI_REGISTRY_IMAGE:$IMAGE_VERSION
  deploy_to_rinkeby_metamask:
      image: docker:git
      services:
      - docker:dind
      type: 
        ethereum/deploy: 
          signing: true
          record: true
      script:
      - IMAGE_VERSION=$(git rev-parse HEAD)
      - docker pull $CI_REGISTRY_IMAGE:$IMAGE_VERSION
      - docker run --rm -i -e INFURA_API_KEY=${INFURA_API_KEY} -e SUPERBLOCKS_SESSIONID="${SUPERBLOCKS_SESSIONID}" -e NETWORK=rinkeby_metamask $CI_REGISTRY_IMAGE:$IMAGE_VERSION

stages:
  - test:
      jobs:
        - test1
        - test2
  - deploy_to_rinkeby:
      jobs:
        - deploy_to_rinkeby
      filters:
        only:
          - tags
  - deploy_to_mainnet:
      jobs:
        - deploy_to_mainnet
      filters:
        only:
          - manual
