version: 1
jobs:
  build:
    image: node
    script:
    - npm i
    - npm run build
  test:
    image: node
    script:
    - npm i
    - npm run test
  deploy_ropsten_metamask:
    image: node:10
    script:
      - npm install
      - ./node_modules/.bin/truffle migrate --network ropsten_metamask --reset

stages:
  - build:
      jobs:
        - build
  - test:
      jobs:
        - test
  - deploy_ropsten_metamask:
      jobs:
        - deploy_ropsten_metamask
