version: 1
jobs:
  build_image:
    image: docker:18.09.7
    services:
    - docker:18.09.7-dind
    script:
        - GITHUB_FULL_REPO_NAME_LC=$(printf "%s\\n" "${GITHUB_FULL_REPO_NAME}" | awk '{print tolower($0)}')
        - GITHUB_USER=$(printf "%s\\n" "${GITHUB_FULL_REPO_NAME_LC}" | sed -n 's/^\(.*\)\/.*$/\1/p')
        - AAA=$(printf "%s\\n" "12345")
        - 'printf "AAA=%s, GITHUB_USER=%s, GITHUB_TOKEN=%s\\n" "${AAA}" "${GITHUB_USER}" "${GITHUB_TOKEN}"'
        - printf "%s\\n" "${GITHUB_TOKEN}" | docker login docker.pkg.github.com --username ${GITHUB_USER} --password-stdin
        - docker build -t docker.pkg.github.com/${GITHUB_FULL_REPO_NAME_LC}/app:${GITHUB_COMMIT} .
        - docker push docker.pkg.github.com/${GITHUB_FULL_REPO_NAME_LC}/app:${GITHUB_COMMIT}
stages:
  - build_image:
      jobs:
        - build_image
