version: 1
jobs:
  build:
    image: node:12
    script:
        - npm install
        - npx truffle compile

  test:
    image: node:12
    script:
        - npm install
        - npx truffle test

  deploy_to_rinkeby:
    image: node:12
    type:
        name: ethereum/deploy
    script:
        - npm install
        - npx truffle migrate --network rinkeby --reset

  deploy_to_mainnet:
    image: node:12
    type:
        name: ethereum/deploy
    script:
        - npm install
        - npx truffle migrate --network rinkeby_metamask --reset

        
stages:
  - build_and_test:
      jobs: 
        - build
        - test
  - deploy_to_testnets:
      jobs:
        - deploy_to_rinkeby:
            filters:
              only: 
                - master
  - deploy_to_mainnet:
      jobs:
        - deploy_to_mainnet:
            when: manual
            filters:
              only: 
                - master
