version: 1
jobs:
  test1:
    image: node:10
    script:
        - npm install
        - ./node_modules/.bin/truffle test ./test/simplestorage.js
  test2:
    image: node:10
    script:
        - npm install
        - ./node_modules/.bin/truffle test ./test/TestSimpleStorage.sol
  deploy_ropsten_metamask:
    image: node:10
    script:
        - npm install
        - ./node_modules/.bin/truffle migrate --network ropsten_metamask --reset

stages:
  - test:
      jobs:
        - test1
        - test2
  - deploy_ropsten_metamask:
      jobs:
        - deploy_ropsten_metamask
