version: 1
jobs:
  test1:
    image: node:10
    script:
        - npm install
        - ./node_modules/.bin/truffle test ./test/simplestorage.js
  test2:
    image: node:10
    script:
        - npm install
        - ./node_modules/.bin/truffle test ./test/TestSimpleStorage.sol
stages:
  - test:
      jobs:
        - test1
        - test2
