# Truffle Reference Project

version: 1
jobs:
  push_to_docker_registry:
    image: docker:18.09.7
    services:
      - docker:18.09.7-dind
    script:
      - echo "$GITHUB_REGISTRY_TOKEN" | docker login docker.pkg.github.com --username SuperblocksHQ --password-stdin
      - docker build --build-arg BUILD=build:dev -t $GITHUB_REGISTRY_IMAGE:$SUPER_COMMIT_SHA1 .
      - docker push $GITHUB_REGISTRY_IMAGE:$SUPER_COMMIT_SHA1
      
  deploy_ropsten_metamask:
    image: $GITHUB_REGISTRY_IMAGE:$SUPER_COMMIT_SHA1
    script:
        - npx truffle migrate --network ropsten_metamask --reset

stages:
  - build:
      jobs:
        - push_to_docker_registry
          filters:
            - only:
                master
  - deploy:
      jobs:
        - deploy_ropsten_metamask
           filters:
            - only:
                master
