version: 1
jobs:
  build_image:
    image: docker:18.09.7
    services:
    - docker:18.09.7-dind
    script:
        - printf "fullrepo: %s\\n" "${GITHUB_FULL_REPO_NAME}"
        - printf "username: %s\\n" "${GITHUB_FULL_REPO_NAME}" | sed -n 's/.*\/\(.*\)\/.*$/\1/p'
        - GITHUB_USER=$(printf "%s" "${GITHUB_FULL_REPO_NAME}" | sed -n 's/.*\/\(.*\)\/.*$/\1/p')
        - 'printf "GITHUB_USER=%s, GITHUB_TOKEN=%s\\n" "${GITHUB_USER}" "${GITHUB_TOKEN}"'
        - docker build -t docker.pkg.github.com/${GITHUB_FULL_REPO_NAME}/app:${GITHUB_COMMIT} .
        - docker push docker.pkg.github.com/${GITHUB_FULL_REPO_NAME}/app:${GITHUB_COMMIT}
stages:
  - build_image:
      jobs:
        - build_image
